---
title: Digidem Lab
timezone: UTC
collections:
  projects:
    title: Projects
    output: true
    permalink: "/:title/"
  crew:
    title: Crew
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    lang: sv
- scope:
    path: en
    type: pages
  values:
    layout: page
    lang: en
- scope:
    path: ''
    type: projects
  values:
    layout: page
    lang: sv
- scope:
    path: ''
    type: posts
  values:
    layout: project
    lang: sv
- scope:
    path: ''
    type: crew
  values:
    lang: sv
permalink: "/projects/:title/"
email: admin@digidemlab.org
news:
  sv:
    title: Nyheter
    more: Fler nyheter
  en:
    title: News
    more: More news
contact:
  sv:
    title: Prata med oss!
    text: Hör av dig om du har en idé till ett spännande projekt!
  en:
    title: Get in touch!
    text: Digidem Lab is a non-profit organisation promoting participatory democracy
      on all levels of society. Get in touch to talk about project ideas or cooperation!
contact-services:
  sv:
    title: Vill du veta mer?
    text: Kontakta oss för att diskutera gemensamma projekt eller få ett prisförslag på våra tjänster.
  en:
    title: Get in touch!
    text: Digidem Lab is a non-profit organisation promoting participatory democracy
      on all levels of society. Get in touch to talk about project ideas or cooperation!
partner-text:
  sv: Labbet drivs med hjälp av Allmänna Arvsfonden och ABF Göteborg i samarbete
    med Sveriges Kommuner och Landsting, Miljöpartiet de Gröna, LSU - Sveriges ungdomsorganisationer,
    Ung Media och Unga Rörelsehindrade Göteborgsklubben.
  en: Digidem Open Lab is co-organised with ABF Göteborg, with the support of Allmänna
    Arsvfonden and the cooperation of Sweden's Municipalities, The Swedish Green Party,
    The National Council of Swedish Youth Organisations (LSU), Young Media and Unga
    Rörelsehindrade Gothenburg.
partner-links:
- name: ABF
  logo: "/uploads/logotyp-abf.png"
  link: http://www.abf.se/goteborg
- name: Allmänna Arvsfonden
  logo: "/uploads/logotyp-arvsfonden.png"
  link: http://www.arvsfonden.se/
questions:
  sv: Projektledare
  en: Project manager
project-title:
  sv: Projekt
  en: Projects
lab-title:
  sv: "Labbet :bulb:"
  en: "Lab :bulb:"
lab-desc:
  sv: I labbet utvecklar vi framtidens digitala tjänster för deltagande och demokrati.
lab-link:
  sv: Mer om labbet
  en: More projects
baseurl:
url: https://digidemlab.org
author: Digidem Lab
twitter:
  username: digidemlab
facebook:
  publisher: digidemlab
logo: "/assets/logotyp.png"
social:
  links:
  - https://twitter.com/digidemlab
  - https://www.facebook.com/digidemlab
  - https://www.instagram.com/digidemlab/
  - https://github.com/digidemlab
github_username: p-jo
repository: digidemlab/digidemlab.github.io
markdown: kramdown
exclude:
- ".sass-cache"
- bower_components
- path
theme: minima
sass:
  sass_dir: _sass
plugins:
- jemoji
- jekyll-seo-tag
- jekyll-redirect-from
t:
  sv:
    mission: Digidem Lab erbjuder tjänster och utvecklar metoder och verktyg för framtidens deltagande demokrati.
    language: Svenska
    member:
    - title: Styrelsemedlem och medgrundare till internationella Consul Democracy Foundation.
      image: /assets/images/logo-consul.png
      url: https://consulproject.org
    - title: Vi utvecklar metoder för medborgardialog i Göteborg och Stockholm med stöd av Vinnova.
      image: /assets/images/logo-vinnova.png
    - title: Medlem i Global Participatory Budgeting Hub.
      image: /assets/images/logo-pbp.png
      url: https://www.participatorybudgeting.org/globalpbhub/
  en:
    mission: Digidem Lab erbjuder tjänster och utvecklar metoder och verktyg för framtidens deltagande demokrati.
    language: English
