# Site settings
title: Petter Joelson

email: petter@p-jo.se
description: "Activist & Web Strategist"
baseurl: ""
author: "Petter Joelson"
twitter_username: p_jo
github_username:  p-jo

# Build settings
markdown: kramdown
# relative_permalinks: true
permalink: pretty

# Multilingual settings
# See https://github.com/tristen/multilingual
# permalink: /:categories/:title
# languages:
#   - name: 'English'
#     key: 'en'
#   - name: 'Espa√±ol'
#     key: 'es'

# Prose settings
# See https://github.com/prose/prose/wiki
prose:
  rooturl: '_posts'

# Settings
exclude:  [".sass-cache", "bower_components"]
